version: '3.8'  
services:  
  login-action:  
    build:  
      context: .  
      dockerfile: dev.Dockerfile  
    volumes:  
      - .:/app  
      - /app/node_modules  
    environment:  
      - NODE_ENV=development