version: '3.8'  
services:  
  login-action:  
    build:  
      context: .  
      dockerfile: dev.Dockerfile  
      target: test  
    volumes:  
      - .:/src  
      - reports:/src/reports  
      - coverage:/tmp/coverage  
    environment:  
      - NODE_ENV=test  
      - RUNNER_TEMP=/tmp/github_runner  
      - RUNNER_TOOL_CACHE=/tmp/github_tool_cache  
      - JEST_JUNIT_OUTPUT_DIR=/src/reports/  
      - JEST_JUNIT_OUTPUT_NAME=junit.xml  

volumes:  
  reports:  
  coverage: