name: Integration Tests  

on: [push, pull_request]  

jobs:  
  integration-test:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      
      - name: Set up Docker  
        uses: docker/setup-buildx-action@v1  
      
      - name: Run Integration Tests  
        run: |  
          docker-compose up -d  
          npm install  
          npm run test:integration  
        env:  
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}