name: Integration Tests  

on: [push, pull_request]  

jobs:  
  integration-test:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      
      - name: Set up Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '20'  

      - name: Setup yarn  
        run: |  
          npm install -g yarn  
          yarn --version  

      - name: Install dependencies  
        run: |  
          yarn install --network-timeout 300000  
        env:  
          NODE_ENV: development  

      - name: Create test directories  
        run: |  
          mkdir -p reports  
          mkdir -p coverage  
          mkdir -p $RUNNER_TEMP  
          mkdir -p $RUNNER_TOOL_CACHE  
          chmod -R 777 reports coverage $RUNNER_TEMP $RUNNER_TOOL_CACHE  
        env:  
          RUNNER_TEMP: /tmp/github_runner  
          RUNNER_TOOL_CACHE: /tmp/github_tool_cache  

      - name: Run integration tests  
        run: |  
          yarn run test:integration  
        env:  
          RUNNER_TEMP: /tmp/github_runner  
          RUNNER_TOOL_CACHE: /tmp/github_tool_cache  
          NODE_ENV: test  
          JEST_JUNIT_OUTPUT_DIR: ./reports  
          JEST_JUNIT_OUTPUT_NAME: junit.xml  
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}  
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Upload test results  
        if: always()  
        uses: actions/upload-artifact@v3  
        with:  
          name: test-reports  
          path: |  
            reports/  
            coverage/