name: Metrics Collection  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  metrics:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  
      packages: read  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4  
        with:  
          fetch-depth: 0  
          persist-credentials: false  
          token: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Setup Node.js  
        uses: actions/setup-node@v4  
        with:  
          node-version: '18.19.0'  
          cache: 'npm'  
      
      - name: Configure Git  
        run: |  
          git config --global user.name "github-actions[bot]"  
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  
      
      - name: Install dependencies  
        run: |  
          npm ci  
          npm install -g typescript  
      
      - name: Run tests with coverage  
        run: npm run test:coverage  
      
      - name: Check build time  
        run: |  
          START_TIME=$SECONDS  
          npm run build  
          ELAPSED_TIME=$(($SECONDS - $START_TIME))  
          echo "Build took $ELAPSED_TIME seconds"