name: Test Automation  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  schedule:  
    - cron: '*/5 * * * *'  

jobs:  
  test:  
    runs-on: ubuntu-latest  
    
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Setup Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '18.19.0'  
          cache: 'npm'  

      - name: Install dependencies  
        run: npm ci  

      # Ejecutar pruebas  
      - name: Run Tests  
        run: |  
          npm run test  
          npm run test:integration  
        continue-on-error: true  

      # Ejecutar análisis de código  
      - name: Run Linting  
        run: npm run lint  
        continue-on-error: true  

      # Generar reportes  
      - name: Generate Reports  
        if: always()  
        run: npm run generate-report  
        continue-on-error: true  

      # Subir reportes  
      - name: Upload Test Reports  
        if: always()  
        uses: actions/upload-artifact@v3  
        with:  
          name: test-results  
          path: reports/