name: "OWASP ZAP Scan"  

on:  
  push:  
    branches: [ master ]  
  schedule:  
    - cron: '0 0 * * 0'  

jobs:  
  zap_scan:  
    runs-on: ubuntu-latest  
    name: Scan the application  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
      
      - name: ZAP Scan  
        uses: zaproxy/action-full-scan@v0.12.0  
        with:  
          token: ${{ secrets.GITHUB_TOKEN }}  
          docker_name: 'owasp/zap2docker-stable'  
          target: 'http://localhost:3000'  
          rules_file_name: '.zap/rules.tsv'  
          cmd_options: '-a'